# Generated by Django 4.1.1 on 2022-09-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_pedido_producto_pedido_id_transaccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dir_despacho',
            new_name='DirDespacho',
        ),
        migrations.RenameModel(
            old_name='prod_pedido',
            new_name='ProdPedido',
        ),
    ]
