# Generated by Django 4.1.1 on 2022-09-29 06:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0004_rename_dir_despacho_dirdespacho_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cliente',
            new_name='Clientes',
        ),
        migrations.RenameModel(
            old_name='pedido',
            new_name='Pedidos',
        ),
        migrations.RenameModel(
            old_name='producto',
            new_name='Productos',
        ),
    ]
